[package]
name = "websocket-server"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21"
clap = { version = "4.4.7", features = ["derive"] }
futures = "0.3"
futures-timer = "3"
libp2p = { workspace = true, features = ["dns", "identify", "kad", "macros", "noise", "tokio", "relay", "request-response", "tcp", "wasm-bindgen", "websocket-websys", "websocket", "yamux", "autonat", "ping"] }
serde = "1.0.190"
serde_derive = "1.0.125"
serde_json = "1.0"
tokio = { version = "1", features = ["sync", "macros", "io-util", "rt", "time"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
zeroize = "1"
sha2 = { version = "0.10.8" }

[lints]
workspace = true
